version: '3'
services:
  db:
    image: mysql/mysql-server:5.7.22-1.1.5
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd1
      MYSQL_DATABASE: api
      MYSQL_USER: user1
      MYSQL_PASSWORD: P@ssw0rd
  app:
    build: .
    links:
      - db
    ports:
      - "8083:8083"
    #working_dir: /usr/local/FinchSlickGradleAPIV1